#!/bin/bash

echo "🔐 GUÍA PARA CONFIGURAR SECRETS EN GITHUB"
echo "=========================================="
echo ""

echo "📋 SECRETS QUE NECESITAS CONFIGURAR:"
echo "====================================="
echo ""
echo "🔑 SERVER_HOST"
echo "   Valor: trespuntoscomunicacion.es"
echo "   Descripción: Host del servidor de destino"
echo ""
echo "🔑 SERVER_USER"
echo "   Valor: cursor"
echo "   Descripción: Usuario para conectarse al servidor"
echo ""
echo "🔑 SERVER_PASSWORD"
echo "   Valor: 5#!OWwzue465&OO(N5"
echo "   Descripción: Contraseña del usuario del servidor"
echo ""
echo "🔑 SERVER_PORT"
echo "   Valor: 22"
echo "   Descripción: Puerto SSH del servidor"
echo ""

echo "🌐 PASOS PARA CONFIGURAR:"
echo "=========================="
echo ""
echo "1. 📁 Ve a tu repositorio en GitHub:"
echo "   https://github.com/TresPuntos/dashboard-horas"
echo ""
echo "2. ⚙️ Haz click en 'Settings' (pestaña superior)"
echo ""
echo "3. 🔐 En el menú lateral izquierdo, busca 'Secrets and variables'"
echo "   Luego haz click en 'Actions'"
echo ""
echo "4. ➕ Haz click en 'New repository secret'"
echo ""
echo "5. 📝 Para cada secret:"
echo "   • Escribe el nombre (ej: SERVER_HOST)"
echo "   • Pega el valor correspondiente"
echo "   • Haz click en 'Add secret'"
echo "   • Repite para los 4 secrets"
echo ""

echo "📊 VERIFICACIÓN:"
echo "================="
echo ""
echo "Después de configurar los 4 secrets, deberías ver:"
echo "• SERVER_HOST"
echo "• SERVER_PASSWORD"
echo "• SERVER_PORT"
echo "• SERVER_USER"
echo ""

echo "🚀 ACTIVAR DEPLOYMENT:"
echo "======================"
echo ""
echo "Una vez configurados los secrets:"
echo "1. Ve a: https://github.com/TresPuntos/dashboard-horas/actions"
echo "2. Haz click en el workflow 'Deploy Dashboard to Server'"
echo "3. Haz click en 'Run workflow'"
echo "4. Selecciona la rama 'main'"
echo "5. Haz click en 'Run workflow'"
echo ""

echo "📋 URLS IMPORTANTES:"
echo "===================="
echo ""
echo "🔗 Configurar secrets:"
echo "   https://github.com/TresPuntos/dashboard-horas/settings/secrets/actions"
echo ""
echo "🔗 Ver GitHub Actions:"
echo "   https://github.com/TresPuntos/dashboard-horas/actions"
echo ""
echo "🔗 Dashboard final:"
echo "   https://trespuntoscomunicacion.es/db-clientes/"
echo ""

echo "✅ Una vez configurados los secrets, el deployment automático funcionará"
