#!/bin/bash

echo "🔍 VERIFICADOR DE SECRETS CONFIGURADOS"
echo "======================================"
echo ""

echo "📋 DESPUÉS DE CONFIGURAR LOS SECRETS:"
echo "======================================"
echo ""
echo "1. Ve a: https://github.com/TresPuntos/dashboard-horas/settings/secrets/actions"
echo "2. Deberías ver estos 4 secrets:"
echo ""
echo "   ✅ SERVER_HOST"
echo "   ✅ SERVER_PASSWORD" 
echo "   ✅ SERVER_PORT"
echo "   ✅ SERVER_USER"
echo ""

echo "🚀 ACTIVAR EL DEPLOYMENT:"
echo "========================="
echo ""
echo "Una vez que veas los 4 secrets configurados:"
echo ""
echo "1. Ve a: https://github.com/TresPuntos/dashboard-horas/actions"
echo "2. Busca el workflow 'Deploy Dashboard to Server'"
echo "3. Haz click en el workflow"
echo "4. Haz click en 'Run workflow' (botón azul)"
echo "5. Selecciona 'main' en el dropdown"
echo "6. Haz click en 'Run workflow' (botón verde)"
echo ""

echo "⏱️ TIEMPO DE EJECUCIÓN:"
echo "======================="
echo "• El workflow tardará aproximadamente 2-3 minutos"
echo "• Puedes ver el progreso en tiempo real"
echo "• Si hay errores, aparecerán en rojo"
echo ""

echo "✅ RESULTADO ESPERADO:"
echo "======================"
echo "• ✅ Build exitoso"
echo "• ✅ Archivos subidos al servidor"
echo "• ✅ Dashboard actualizado"
echo "• ✅ Integración de Toggl funcionando"
echo ""

echo "🔗 ENLACES DIRECTOS:"
echo "===================="
echo ""
echo "🔐 Configurar secrets:"
echo "   https://github.com/TresPuntos/dashboard-horas/settings/secrets/actions"
echo ""
echo "⚙️ Ejecutar workflow:"
echo "   https://github.com/TresPuntos/dashboard-horas/actions"
echo ""
echo "🌐 Dashboard final:"
echo "   https://trespuntoscomunicacion.es/db-clientes/"
echo ""

echo "📞 SI NECESITAS AYUDA:"
echo "======================"
echo "• Si no ves los secrets, vuelve a crearlos uno por uno"
echo "• Si el workflow falla, revisa los logs en GitHub Actions"
echo "• Si hay errores de conexión, puede ser problema del servidor"
echo ""

echo "✅ ¡Todo listo para configurar los secrets!"
